##################################################################################
#####                                TODO                                    #####
##################################################################################
Todo:
  path: webservice/todo/
  properties:
    id: int?
    title: String
    completed: bool

##################################################################################
#####                                MEAL                                    #####
##################################################################################

MealResponse:
  path: webservice/meal/
  properties:
    meals: List<Meal>?


Meal:
  path: webservice/meal/   
  properties:
    id:
      type: String
      jsonKey: idMeal
    name: 
      type: String
      jsonKey: strMeal
    country:
      type: String?
      jsonKey: strArea
    category: 
      type: String?
      jsonKey: strCategory
    image: 
      type: String
      jsonKey: strMealThumb
    instructions: 
      type: String?
      jsonKey: strInstructions

##################################################################################
#####                                REMOTE CONFIG                           #####
##################################################################################

LocalizedMessage:
  path: data/remote_config
  properties:
    en: String?