##################################################################################
#####                                TODO                                    #####
##################################################################################
Todo:
  path: webservice/todo/
  properties:
    id: int?
    title: String
    completed: bool

##################################################################################
#####                                MEAL                                    #####
##################################################################################

Meal:
  path: webservice/meal/   
  properties:
    id: String
    name: String
    country: String
    category: String
    image: String

##################################################################################
#####                                REMOTE CONFIG                           #####
##################################################################################

LocalizedMessage:
  path: data/remote_config
  properties:
    en: String?